# Generated by Django 3.1 on 2020-12-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
